{% if request.lang == 'pt' %}
<h4>Informação</h4>
<p>Interface de Publicação de Tesauros do LASeD (Input-LASeD) é uma plataforma web para publicação de tesauros gerenciado pelo grupo de pesquisa LASeD da Universidade Estadual do Centro-Oeste (Unicentro). Esta plataforma utiliza a interface Skosmos para possibilitar uma melhor interação do usuários.</p>
{% elseif request.lang == 'pt-BR' %}
<h4>Informação</h4>
<p>Interface de Publicação de Tesauros do LASeD (Input-LASeD) é uma plataforma web para publicação de tesauros gerenciado pelo grupo de pesquisa LASeD da Universidade Estadual do Centro-Oeste (Unicentro). Esta plataforma utiliza a interface Skosmos para possibilitar uma melhor interação do usuários.</p>
{% elseif request.lang == 'en' %}
<h4>About</h4>
<p>LASeD Thesaurus publishing interface (Input-LASeD) is a web platform for publishing thesauruses managed by the LASeD research group at the Midwestern State University (Unicentro). This platform uses the Skosmos interface to enable better user interaction.</p>
{% endif %}
